language: python
sudo: false
python:
    - "2.7"
branches:
  only:
    - master
    - /^v[0-9].*$/
addons:
    apt:
        packages:
            - gfortran
            - r-base-dev
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
    # Update conda
    - conda update --yes conda
install:
    # Create conda matching requirements
    - conda env create -n test python=$TRAVIS_PYTHON_VERSION -f environment.yaml
    - source activate test
    # Rest of dependencies
    - "pip install -r requirements/dev.txt"
    - "pip install pytest"
    # Install YATSM
    - "pip install -e ."
script:
    - py.test tests/
    - coverage run --source yatsm -m py.test
after_success:
    - pip install coveralls
    - coverage report
    - coveralls
