language: python
sudo: false
cache:
    directories:
        - $HOME/conda/pkgs
python:
    - "2.7"
branches:
    only:
        - master
        - /^v[0-9].*$/
addons:
    apt:
        packages:
            - gfortran
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
    # Update conda
    - conda update --yes conda
install:
    # Create conda matching requirements
    - conda env create -n test python=$TRAVIS_PYTHON_VERSION -f environment.yaml
    - source activate test
    # Rest of dependencies
    - "pip install -r requirements/dev.txt"
    - "pip install pytest"
    # Install YATSM
    - "pip install -e ."
script:
    - py.test -ra tests/
    # Disable numba JIT for coverage to correctly identify JIT-ed lines
    # See: http://stackoverflow.com/questions/26875191/analyzing-coverage-of-numba-wrapped-functions
    - NUMBA_DISABLE_JIT=1 coverage run --source yatsm -m py.test
after_success:
    - pip install coveralls
    - coverage report
    - coveralls
before_cache:
    # Deactivate conda so we use system 'curl'
    - source deactivate
